exports.db = `CREATE TABLE IF NOT EXISTS Users(
	id INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	introductionOfUser VARCHAR(255),
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	dob DATETIME,
	profilePictureUrl VARCHAR(255),
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Listings (
	id INT NOT NULL AUTO_INCREMENT,
	hostID INT NOT NULL,
	pricePerDay INT NOT NULL,
	miscCostPercentage INT NOT NULL,
	address VARCHAR(255) NOT NULL,
	listingDescription VARCHAR(255),
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME NOT NULL,
	avgRating FLOAT NOT NULL,
	cityId INT NOT NULL,
	features INT NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Booking (
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	listingId INT NOT NULL,
	checkinDate DATE NOT NULL,
	checkoutDate DATE NOT NULL,
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME NOT NULL,
	totalCost FLOAT NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Reviews (
	id INT NOT NULL AUTO_INCREMENT,
	reviewerId INT NOT NULL,
	revieweeId BINARY NOT NULL,
	description TEXT,
	rating INT NOT NULL,
	createdAt DATETIME NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS city (
	id INT NOT NULL AUTO_INCREMENT,
	cityName VARCHAR(255) NOT NULL,
	stateId INT NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS state (
	id INT NOT NULL AUTO_INCREMENT,
	stateName VARCHAR(255) NOT NULL,
	countryId INT NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS country (
	id INT NOT NULL AUTO_INCREMENT,
	countryName VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Features (
	id INT NOT NULL AUTO_INCREMENT,
	typeofListing varchar(100) NOT NULL,
	bedrooms INT NOT NULL,
	bathrooms INT NOT NULL,
	beds INT NOT NULL,
	maxOccupants INT NOT NULL,
	policies blob(255) NOT NULL,
	amenities blob(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Payments (
	id INT NOT NULL AUTO_INCREMENT,
	bookingId INT NOT NULL,
	TransactionID VARCHAR(255) NOT NULL UNIQUE,
	totalPaymentAmount FLOAT NOT NULL,
	createdAt DATETIME NOT NULL,
	PaymentStatus VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS Image (
	id INT NOT NULL AUTO_INCREMENT,
	entityId INT NOT NULL,
	url VARCHAR(255) NOT NULL,
	alt VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS bookmark (
	id INT NOT NULL AUTO_INCREMENT,
	listingId INT NOT NULL,
	userId INT NOT NULL,
	PRIMARY KEY (id)
);
ALTER TABLE Listings
ADD CONSTRAINT Listings_fk0 FOREIGN KEY (hostID) REFERENCES Users(id);
ALTER TABLE Listings
ADD CONSTRAINT Listings_fk1 FOREIGN KEY (cityId) REFERENCES city(id);
ALTER TABLE Listings
ADD CONSTRAINT Listings_fk2 FOREIGN KEY (features) REFERENCES Features(id);
ALTER TABLE Booking
ADD CONSTRAINT Booking_fk0 FOREIGN KEY (userId) REFERENCES Users(id);
ALTER TABLE Booking
ADD CONSTRAINT Booking_fk1 FOREIGN KEY (listingId) REFERENCES Listings(id);
ALTER TABLE city
ADD CONSTRAINT city_fk0 FOREIGN KEY (stateId) REFERENCES state(id);
ALTER TABLE state
ADD CONSTRAINT state_fk0 FOREIGN KEY (countryId) REFERENCES country(id);
ALTER TABLE Payments
ADD CONSTRAINT Payments_fk0 FOREIGN KEY (bookingId) REFERENCES Booking(id);
ALTER TABLE Image
ADD CONSTRAINT Image_fk0 FOREIGN KEY (entityId) REFERENCES Listings(id);
ALTER TABLE bookmark
ADD CONSTRAINT bookmark_fk0 FOREIGN KEY (listingId) REFERENCES Listings(id);
ALTER TABLE bookmark
ADD CONSTRAINT bookmark_fk1 FOREIGN KEY (userId) REFERENCES Users(id);`;
